### ISSUE TITLE
Please reconsider "option #7"

### ISSUE THREAD

**Issue by bjmiller** [martinheidegger/es6modules-nodejs#18]
Please don't unilaterally cross off "don't do this".  It is the most valid answer.

It's undeniably crystal clear that the spec for ES2015 modules was done completely incorrectly, and needs to go back for another round of review.  It appears to be intentionally designed to break everything, it should not be allowed to be implemented anywhere.  Having the Node Foundation put their foot down and say "NO" would send a strong message to the other players in the ecosystem that the spec must be redone differently, and move the members of th TC to take it up again and do it right.

**Comment by ljharb** [comment]
In no way is it a valid answer. If node does nothing, then ES modules are DOA. I can assure you, the module spec will never change in a way that removes the need for some form of parse goal detection.

Either node ships an implementation that meets as many use cases as possible, and thus everyone else imlpements it (or a compatible form of it), or ES modules just won't happen - and that would be a net loss for everybody.

**Comment by martinheidegger** [comment]
@bjmiller 

> because there is **lack of evidence** that anyone in the community supports to not go with the times.

Please provide a PR with more evidence (information)
