### ISSUE TITLE
Mention Webpack 2 support?

### ISSUE THREAD

**Issue by clavecoder** [martinheidegger/es6modules-nodejs#19]
Webpack 2, in beta, also supports ES2015 modules. You may want to mention that.

See https://www.npmjs.com/package/babel-preset-es2015-webpack

**Comment by ljharb** [comment]
Since the loader spec isn't complete, nothing truly "supports" ES6 modules yet. Webpack2 is only guessing at the eventual spec.

**Comment by martinheidegger** [comment]
Since babel-preset-es2015 is deprecated I close this issue.
