### ISSUE TITLE
Another propsal

### ISSUE THREAD

**Issue by zenparsing** [martinheidegger/es6modules-nodejs#9]
There's also this:

https://github.com/zenparsing/es6-node-modules

which has been mentioned a bit in various threads.  Not sure if it meets your criteria for inclusion, but I wanted to throw it out there.

**Comment by williamkapke** [comment]
There are 7 options currently on the table. [This was just discussed at NodeConf this weekend](https://twitter.com/williamkapke/status/741413610014920705).

The option that is often left off is "Do nothing"... which is being considered as seriously as all the others.

**Comment by martinheidegger** [comment]
@zenparsing Adding that proposal to this document would be awesome. If you have a minute, I would welcome a PR.

@williamkapke Will continue to discuss this in issue #10

**Comment by martinheidegger** [comment]
@zenparsing I opened #13 and would welcome your +1
